name = "prayerwall-frontend"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]


[vars]
PUBLIC_API_BASE_URL = "https://api.prayerwall.space"
SITE = "https://prayerwall.space"

[observability]
enabled = true
