name = "prayerwall-space"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[[kv_namespaces]]
binding = "SESSION"

[vars]
PUBLIC_API_BASE_URL = "https://prayerwall-web-service.onrender.com"
SITE = "https://prayerwall.space"
